-- MySQL Script generated by MySQL Workbench
-- Чт 25 июл 2019 14:34:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `register_date` TIMESTAMP NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`)
);

-- -----------------------------------------------------
-- Table `shop`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `customer_email` VARCHAR(255) NOT NULL,
  `payment_info` VARCHAR(255),
  PRIMARY KEY (`customer_id`),
  FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
);

-- -----------------------------------------------------
-- Table `shop`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255),
  `street_no` VARCHAR(255),
  `unit_no` VARCHAR(255),
  `city` VARCHAR(255),
  `country` VARCHAR(255),
  `other` VARCHAR(255),
  PRIMARY KEY (`address_id`)
);

-- -----------------------------------------------------
-- Table `shop`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seller` (
  `seller_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `seller_name` VARCHAR(255) NOT NULL,
  `seller_email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`seller_id`),
  FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
  );

-- -----------------------------------------------------
-- Table `shop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `date_modified` TIMESTAMP NOT NULL,
  `description` TEXT NOT NULL,
  `stock` INT NOT NULL,
  `unit_cost` FLOAT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  FOREIGN KEY (`seller_id`) REFERENCES `seller` (`seller_id`)
  );

-- -----------------------------------------------------
-- Table `shop`.`shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`shipping` (
  `shipping_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL, -- delivery or pickup at pickup points
  `shipping_cost` FLOAT NOT NULL,
  PRIMARY KEY (`shipping_id`)
  );

-- -----------------------------------------------------
-- Table `shop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NOT NULL,
  `date_created` TIMESTAMP NOT NULL,
  `sub_total` FLOAT NOT NULL,
  `customer_id` INT NOT NULL,
  `shipping_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`),
  FOREIGN KEY (`shipping_id`) REFERENCES `shipping` (`shipping_id`)
  );

-- -----------------------------------------------------
-- Table `shop`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_item` (
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`product_id`,`order_id`),
  FOREIGN KEY (`product_id`) REFERENCES `product` (`product_id`),
  FOREIGN KEY (`order_id`) REFERENCES `order` (`order_id`)
  );

-- -----------------------------------------------------
-- Table `shop`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `sub_total` FLOAT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`),
  FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`)
  );

-- -----------------------------------------------------
-- Table `shop`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`cart_item` (
  `product_id` INT NOT NULL,
  `cart_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`product_id`, `cart_id`),
  FOREIGN KEY (`product_id`) REFERENCES `product` (`product_id`),
  FOREIGN KEY (`cart_id`) REFERENCES `cart` (`cart_id`)
  )

ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
